### ISSUE TITLE
Crashes Tampermonkey Dolphin for Android

### ISSUE THREAD

**Issue by Slofe** [bewam/fetlife_all_members_-ASL-role-status_filter-#1]
As the title says. Whenever I load fetlife with your script installed it crashes tampermonkey so I can't run the script. When I uninstall your script the problem goes away. This is using the latest version of tampermonkey with Dolphin browser on Android 4.4.

**Comment by bewam** [comment]
I'd like to help. I'll find an issue if:
* I can reproduce your exotic configuration.
* I can find a way to debug the tampermonkey for dolphin browser add-on crash.

It's a bit of challenging, don't you think ?

**Comment by bewam** [comment]
Do you have a message like "Tampermonkey detected a problem which prevents the add-on to from running properly..." ?

**Comment by Slofe** [comment]
Hi and thanks for the replies. It doesn't say anything other than  'Unfortunately, Tampermonkey Dolphin has stopped.' This is on my tablet.

I tried it on my phone which runs lollipop . Tampermonkey says the script is running but it doesn't show anything when I look at a list of members. Tampermonkey doesn't crash on my phone though.

**Comment by Slofe** [comment]
No luck with fixing this issue?

**Comment by bewam** [comment]
My attempts to run your configuration failed. I tried to run ecmascript 5-friendly version, the emulated dolphin failed. Actually, I have no solution for the script to run on this platform. I need at least a minimum debugging info to be able to correct or say it's not the script fault. The browser seems pretty opaque.

**Comment by bewam** [comment]
@Slofe: Can you try the code you can find at https://github.com/bewam/fetlife_all_members_-ASL-role-status_filter-/blob/es5/fetlife_all_members_(ASL%2Brole%2Bstatus_filter).user.js
I changed all I know to suit a EcmaScript version 5 engine (2014', old version).
I expect it to work.

**Comment by Slofe** [comment]
Thanks again for your efforts on this. I have good news and bad news. The good news is the script actually runs.  I get boxes appearing on screen for inputting age, role, gender and so on and these appear when a list of members is on screen.  The bad news is when I click 'view all` after entering parameters, nothing happens. Not sure if this is me using it incorrectly but I don't think so as it seems very straight forward.

**Comment by bewam** [comment]
Ok, I did it with the tampermonkey technique, they use [babeljs](https://babeljs.io/). I didn't see it before. The trick consists on making javascript writing old javascript. I managed to test it on a real android device. It works.
I'll try to maintain the ES5 branch, too.
Feel free to reopen.

**Comment by Slofe** [comment]
Hey, just wanted to let you know it's working perfectly now. Thanks for fixing it :)
