### ISSUE TITLE
Not loading search boxes on Violentmonkey

### ISSUE THREAD

**Issue by Slofe** [bewam/fetlife_all_members_-ASL-role-status_filter-#2]
Hello again!

I got fed up with dolphin running so slow on my setup so I have switched to Opera Mobile Labs 12.0.  This is the only version that runs userscripts on Android.  I installed your excellent script and Violentmonkey recognises and runs it but, like on tampermonkey before, it doesn't load any search boxes so I can't run any searches at the moment.  I hope this is an easy fix for you and hope you had a good Christmas and New Year.  Cheers.

**Comment by bewam** [comment]
Did you try both versions ? The [es5](https://github.com/bewam/fetlife_all_members_-ASL-role-status_filter-/raw/es5/fetlife_all_members_(ASL%2Brole%2Bstatus_filter).user.js) legacy one and the [es6](https://github.com/bewam/fetlife_all_members_-ASL-role-status_filter-/raw/master/fetlife_all_members_(ASL%2Brole%2Bstatus_filter).user.js) which is mostly for desktop (recent browsers).
I'd need error logs, the year would start even better for me.
Have a good year.

**Comment by Slofe** [comment]
I just tried both and tried them both under desktop mode and tablet mode. It's the same result for both.  Sorry I don't know how to get error logs.

**Comment by bewam** [comment]
Solved ?

**Comment by Slofe** [comment]
No not solved. Up to you if you wanna work on it but I found another browser. Please see other issue (I will definitekly buy you a beer for being a royal pain in the arse!)
